### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [soozie/jammming#5]
(Exceeds Expectations)

Well done on this project! It seems you have taken on the challenge to complete this project without the step-by-step guide provided - very impressive work! :) It looks like you have a solid understanding of the overall structure of the app as well as each individual component. And great job with the requests to the Spotify API, including chaining the `.then()` methods and error handling. 

As a further challenge, continue to explore the Spotify API and see if you're able to add more features to this app. As you do, be sure to pay attention to the required parameters for making a request to an endpoint, and make sure they are satisfied so it does not result in an error (#1). Happy coding!

**Comment by soozie** [comment]
Wow that's amazing ! Thank you very much for your comment, I really appreciate it! I've tried to follow your advises and correct the highlighted issues. I still need a lot of practice, so I plan on going on practicing adding more and more features.
